[profile.default]
src = 'lib'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
allow_paths = ['../']

remappings = [
    '@fhevm-host-contracts/=../host-contracts/',
    '@fhevm-foundry/=../host-contracts/fhevm-foundry/',
]
