name: test-trigger-build

on:
  workflow_dispatch:
  push:
    branches:
      - aw/ci/e2e-tests-orchestrator

permissions:
  actions: write
  contents: read

jobs:
  trigger-single-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger test-suite build
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const ref = '${{ github.event.inputs.target_ref }}' || context.ref.replace('refs/heads/', '');
            
            console.log(`Attempting to trigger test-suite-docker-build.yml on ref: ${ref}`);
            
            try {
              const response = await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'test-suite-docker-build.yml',
                ref: ref
              });
              
              console.log('✅ Successfully triggered test-suite-docker-build.yml');
              console.log('Response status:', response.status);
            } catch (error) {
              console.log('❌ Failed to trigger workflow:', error.message);
              console.log('Error details:', JSON.stringify(error.response?.data || error, null, 2));
              core.setFailed(`Failed to trigger workflow: ${error.message}`);
            }
